[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    t-vk/ESP32 BLE Keyboard @ ^0.3.2
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    thomasfredericks/Bounce2 @ ^2.71
